workflows:
    react-native:
        name: reactnativeappsigning
        instance_type: mac_mini
        environment:
            vars:
                XCODE_WORKSPACE: "sqflite"
                XCODE_SCHEME: "sqflite"
            node: latest
        scripts:
            - npm install
            - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - |
                # build iOS
                cd ios
                pod install
                xcodebuild build -workspace "$XCODE_WORKSPACE.xcworkspace" -scheme "$XCODE_SCHEME" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
