workflows:
    react-native:
        name: RNsqlite
        scripts:
            - npm install 
            - echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
            - |
                # build Android
                #react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res
                cd android
                ./gradlew assembleDebug
        artifacts:
            - android/app/build/outputs/**/**/*.apk
        publishing:
            email:
                recipients:
                    - chammounchakhap.vdoit@gmail.com
